// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/cache_image.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheImage struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	Fsid                 string   `protobuf:"bytes,3,opt,name=Fsid,proto3" json:"Fsid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheImage) Reset()         { *m = CacheImage{} }
func (m *CacheImage) String() string { return proto.CompactTextString(m) }
func (*CacheImage) ProtoMessage()    {}
func (*CacheImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_image_b55d73bc10f24dac, []int{0}
}
func (m *CacheImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheImage.Unmarshal(m, b)
}
func (m *CacheImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheImage.Marshal(b, m, deterministic)
}
func (dst *CacheImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheImage.Merge(dst, src)
}
func (m *CacheImage) XXX_Size() int {
	return xxx_messageInfo_CacheImage.Size(m)
}
func (m *CacheImage) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheImage.DiscardUnknown(m)
}

var xxx_messageInfo_CacheImage proto.InternalMessageInfo

func (m *CacheImage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CacheImage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CacheImage) GetFsid() string {
	if m != nil {
		return m.Fsid
	}
	return ""
}

func init() {
	proto.RegisterType((*CacheImage)(nil), "protobuf.Cache_image")
}

func init() {
	proto.RegisterFile("protobuf/cache_image.proto", fileDescriptor_cache_image_b55d73bc10f24dac)
}

var fileDescriptor_cache_image_b55d73bc10f24dac = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x4e, 0x4c, 0xce, 0x48, 0x8d, 0xcf, 0xcc, 0x4d, 0x4c, 0x4f,
	0xd5, 0x03, 0x0b, 0x0a, 0x71, 0xc0, 0xe4, 0x94, 0xdc, 0xb9, 0xb8, 0x9d, 0x11, 0xd2, 0x42, 0x42,
	0x5c, 0x2c, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90,
	0x00, 0x17, 0x73, 0x68, 0x51, 0x8e, 0x04, 0x13, 0x58, 0x08, 0xc4, 0x04, 0xa9, 0x72, 0x2b, 0xce,
	0x4c, 0x91, 0x60, 0x86, 0xa8, 0x02, 0xb1, 0x93, 0xd8, 0xc0, 0x46, 0x1a, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0x8b, 0x9c, 0x6e, 0x77, 0x00, 0x00, 0x00,
}
