// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/checker_image.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckerImage struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:code,code"
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty" gorm:"index:code,code"`
	Url                  string   `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckerImage) Reset()         { *m = CheckerImage{} }
func (m *CheckerImage) String() string { return proto.CompactTextString(m) }
func (*CheckerImage) ProtoMessage()    {}
func (*CheckerImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_checker_image_fc0f7b68b47ed25d, []int{0}
}
func (m *CheckerImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckerImage.Unmarshal(m, b)
}
func (m *CheckerImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckerImage.Marshal(b, m, deterministic)
}
func (dst *CheckerImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckerImage.Merge(dst, src)
}
func (m *CheckerImage) XXX_Size() int {
	return xxx_messageInfo_CheckerImage.Size(m)
}
func (m *CheckerImage) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckerImage.DiscardUnknown(m)
}

var xxx_messageInfo_CheckerImage proto.InternalMessageInfo

func (m *CheckerImage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckerImage) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CheckerImage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckerImage)(nil), "protobuf.Checker_image")
}

func init() {
	proto.RegisterFile("protobuf/checker_image.proto", fileDescriptor_checker_image_fc0f7b68b47ed25d)
}

var fileDescriptor_checker_image_fc0f7b68b47ed25d = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xce, 0x48, 0x4d, 0xce, 0x4e, 0x2d, 0x8a, 0xcf, 0xcc, 0x4d,
	0x4c, 0x4f, 0xd5, 0x03, 0x0b, 0x0b, 0x71, 0xc0, 0x64, 0x95, 0x5c, 0xb9, 0x78, 0x9d, 0x91, 0x15,
	0x08, 0xf1, 0x71, 0x31, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x79, 0xa6,
	0x08, 0x09, 0x71, 0xb1, 0x38, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xa1, 0x45, 0x39, 0x12, 0xcc, 0x60, 0x21, 0x10, 0x33, 0x89, 0x0d,
	0x6c, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x55, 0xa6, 0xf6, 0x77, 0x00, 0x00, 0x00,
}
