// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/checker_fs.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckerFs struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:code,code"
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty" gorm:"index:code,code"`
	Url                  string   `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckerFs) Reset()         { *m = CheckerFs{} }
func (m *CheckerFs) String() string { return proto.CompactTextString(m) }
func (*CheckerFs) ProtoMessage()    {}
func (*CheckerFs) Descriptor() ([]byte, []int) {
	return fileDescriptor_checker_fs_25bc25616d7e2047, []int{0}
}
func (m *CheckerFs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckerFs.Unmarshal(m, b)
}
func (m *CheckerFs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckerFs.Marshal(b, m, deterministic)
}
func (dst *CheckerFs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckerFs.Merge(dst, src)
}
func (m *CheckerFs) XXX_Size() int {
	return xxx_messageInfo_CheckerFs.Size(m)
}
func (m *CheckerFs) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckerFs.DiscardUnknown(m)
}

var xxx_messageInfo_CheckerFs proto.InternalMessageInfo

func (m *CheckerFs) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckerFs) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CheckerFs) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckerFs)(nil), "protobuf.Checker_fs")
}

func init() {
	proto.RegisterFile("protobuf/checker_fs.proto", fileDescriptor_checker_fs_25bc25616d7e2047)
}

var fileDescriptor_checker_fs_25bc25616d7e2047 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xce, 0x48, 0x4d, 0xce, 0x4e, 0x2d, 0x8a, 0x4f, 0x2b, 0xd6,
	0x03, 0x8b, 0x09, 0x71, 0xc0, 0xa4, 0x94, 0x9c, 0xb8, 0xb8, 0x9c, 0xe1, 0xb2, 0x42, 0x7c, 0x5c,
	0x4c, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x42, 0x5c,
	0x2c, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x00,
	0x17, 0x73, 0x68, 0x51, 0x8e, 0x04, 0x33, 0x58, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0x9b, 0x66, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x86, 0x6a, 0x5c, 0x71, 0x00, 0x00, 0x00,
}
