// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/indexer_manhua_chapter.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexManhuaChapter struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Site                 string               `protobuf:"bytes,2,opt,name=Site,proto3" json:"Site,omitempty"`
	Number               int32                `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Chapter              string               `protobuf:"bytes,4,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	Title                string               `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Update               *timestamp.Timestamp `protobuf:"bytes,6,opt,name=Update,proto3" json:"Update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IndexManhuaChapter) Reset()         { *m = IndexManhuaChapter{} }
func (m *IndexManhuaChapter) String() string { return proto.CompactTextString(m) }
func (*IndexManhuaChapter) ProtoMessage()    {}
func (*IndexManhuaChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_indexer_manhua_chapter_3bbcff22d1fbdeca, []int{0}
}
func (m *IndexManhuaChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexManhuaChapter.Unmarshal(m, b)
}
func (m *IndexManhuaChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexManhuaChapter.Marshal(b, m, deterministic)
}
func (dst *IndexManhuaChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexManhuaChapter.Merge(dst, src)
}
func (m *IndexManhuaChapter) XXX_Size() int {
	return xxx_messageInfo_IndexManhuaChapter.Size(m)
}
func (m *IndexManhuaChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexManhuaChapter.DiscardUnknown(m)
}

var xxx_messageInfo_IndexManhuaChapter proto.InternalMessageInfo

func (m *IndexManhuaChapter) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IndexManhuaChapter) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *IndexManhuaChapter) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *IndexManhuaChapter) GetChapter() string {
	if m != nil {
		return m.Chapter
	}
	return ""
}

func (m *IndexManhuaChapter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *IndexManhuaChapter) GetUpdate() *timestamp.Timestamp {
	if m != nil {
		return m.Update
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexManhuaChapter)(nil), "protobuf.Index_manhua_chapter")
}

func init() {
	proto.RegisterFile("protobuf/indexer_manhua_chapter.proto", fileDescriptor_indexer_manhua_chapter_3bbcff22d1fbdeca)
}

var fileDescriptor_indexer_manhua_chapter_3bbcff22d1fbdeca = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x18, 0x84, 0x49, 0x6d, 0xab, 0x46, 0xf0, 0x10, 0x16, 0x09, 0x7b, 0x2a, 0x82, 0xd0, 0x53, 0x02,
	0xeb, 0x1b, 0xe8, 0xa9, 0x17, 0x0f, 0x75, 0x3d, 0x2f, 0xe9, 0xe6, 0x37, 0x0d, 0x34, 0x4d, 0xc8,
	0xfe, 0x15, 0x7d, 0x31, 0x9f, 0x4f, 0x4c, 0x5b, 0x85, 0xbd, 0xcd, 0x64, 0x86, 0x6f, 0xf2, 0xd3,
	0x87, 0x10, 0x3d, 0xfa, 0x6e, 0x7a, 0x97, 0x76, 0xd4, 0xf0, 0x09, 0xf1, 0xe0, 0xd4, 0xd8, 0x4f,
	0xea, 0x70, 0xec, 0x55, 0x40, 0x88, 0x22, 0xe5, 0xec, 0x6a, 0xad, 0x6d, 0x9f, 0x3e, 0x60, 0xd4,
	0x3e, 0x4a, 0x63, 0xb1, 0x9f, 0x3a, 0x71, 0xf4, 0x4e, 0x1a, 0x3f, 0xa8, 0xd1, 0xc8, 0x3f, 0x52,
	0xc0, 0xaf, 0x00, 0x27, 0x89, 0xd6, 0xc1, 0x09, 0x95, 0x0b, 0xff, 0x6a, 0xa6, 0xdd, 0x7f, 0x13,
	0xba, 0x69, 0x7e, 0xe7, 0xce, 0xc6, 0xd8, 0x2d, 0xcd, 0x1a, 0xcd, 0x49, 0x45, 0xea, 0xbc, 0xcd,
	0x1a, 0xcd, 0x18, 0xcd, 0x5f, 0x2d, 0x02, 0xcf, 0x2a, 0x52, 0x5f, 0xb7, 0x49, 0xb3, 0x3b, 0x5a,
	0xbe, 0x4c, 0xae, 0x83, 0xc8, 0x2f, 0x2a, 0x52, 0x17, 0xed, 0xe2, 0x18, 0xa7, 0x97, 0xcf, 0x33,
	0x86, 0xe7, 0xa9, 0xbe, 0x5a, 0xb6, 0xa1, 0xc5, 0xde, 0xe2, 0x00, 0xbc, 0x48, 0xef, 0xb3, 0x61,
	0x3b, 0x5a, 0xbe, 0x05, 0xad, 0x10, 0x78, 0x59, 0x91, 0xfa, 0x66, 0xb7, 0x15, 0xc6, 0x7b, 0x33,
	0x80, 0x58, 0xef, 0x10, 0xfb, 0xf5, 0xdb, 0xed, 0xd2, 0xec, 0xca, 0x94, 0x3d, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x0b, 0x62, 0x1d, 0xad, 0x36, 0x01, 0x00, 0x00,
}
