// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/indexer_search_item.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexSearchItem struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexSearchItem) Reset()         { *m = IndexSearchItem{} }
func (m *IndexSearchItem) String() string { return proto.CompactTextString(m) }
func (*IndexSearchItem) ProtoMessage()    {}
func (*IndexSearchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_indexer_search_item_dcc8128eabbe504b, []int{0}
}
func (m *IndexSearchItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSearchItem.Unmarshal(m, b)
}
func (m *IndexSearchItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSearchItem.Marshal(b, m, deterministic)
}
func (dst *IndexSearchItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSearchItem.Merge(dst, src)
}
func (m *IndexSearchItem) XXX_Size() int {
	return xxx_messageInfo_IndexSearchItem.Size(m)
}
func (m *IndexSearchItem) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSearchItem.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSearchItem proto.InternalMessageInfo

func (m *IndexSearchItem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IndexSearchItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *IndexSearchItem) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexSearchItem)(nil), "protobuf.Index_search_item")
}

func init() {
	proto.RegisterFile("protobuf/indexer_search_item.proto", fileDescriptor_indexer_search_item_dcc8128eabbe504b)
}

var fileDescriptor_indexer_search_item_dcc8128eabbe504b = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0xcc, 0x4b, 0x49, 0xad, 0x48, 0x2d, 0x8a, 0x2f, 0x4e, 0x4d,
	0x2c, 0x4a, 0xce, 0x88, 0xcf, 0x2c, 0x49, 0xcd, 0xd5, 0x03, 0x4b, 0x0a, 0x71, 0xc0, 0xd4, 0x28,
	0x85, 0x72, 0x09, 0x7a, 0x82, 0x94, 0x21, 0x2b, 0x12, 0xe2, 0xe3, 0x62, 0xf2, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x09, 0x62, 0xf2, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0x0d, 0xc9, 0x2c, 0xc9,
	0x49, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xa4, 0xb8, 0x38, 0x9c, 0x13,
	0x4b, 0x52, 0xd3, 0xf3, 0x8b, 0x2a, 0x25, 0x98, 0xc1, 0x12, 0x70, 0x7e, 0x12, 0x1b, 0xd8, 0x02,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x11, 0x04, 0x36, 0x8d, 0x00, 0x00, 0x00,
}
