// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/m_manhua.proto

package protobuf

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Manhua struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Site                 string   `protobuf:"bytes,2,opt,name=Site" json:"Site,omitempty"`
	Number               int      `protobuf:"varint,3,opt,name=Number" json:"Number,omitempty"`
	Chapter              string   `protobuf:"bytes,4,opt,name=Chapter" json:"Chapter,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title" json:"Title,omitempty"`
	Update               string   `protobuf:"bytes,6,opt,name=Update" json:"Update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manhua) Reset()         { *m = Manhua{} }
func (m *Manhua) String() string { return proto.CompactTextString(m) }
func (*Manhua) ProtoMessage()    {}
func (*Manhua) Descriptor() ([]byte, []int) {
	return fileDescriptor_m_manhua_1b998beee4455e1d, []int{0}
}
func (m *Manhua) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manhua.Unmarshal(m, b)
}
func (m *Manhua) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manhua.Marshal(b, m, deterministic)
}
func (dst *Manhua) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manhua.Merge(dst, src)
}
func (m *Manhua) XXX_Size() int {
	return xxx_messageInfo_Manhua.Size(m)
}
func (m *Manhua) XXX_DiscardUnknown() {
	xxx_messageInfo_Manhua.DiscardUnknown(m)
}

var xxx_messageInfo_Manhua proto.InternalMessageInfo

func (m *Manhua) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Manhua) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *Manhua) GetNumber() int {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Manhua) GetChapter() string {
	if m != nil {
		return m.Chapter
	}
	return ""
}

func (m *Manhua) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Manhua) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

func init() {
	proto.RegisterType((*Manhua)(nil), "protobuf.Manhua")
}

func init() { proto.RegisterFile("protobuf/m_manhua.proto", fileDescriptor_m_manhua_1b998beee4455e1d) }

var fileDescriptor_m_manhua_1b998beee4455e1d = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x8d, 0xcf, 0x4d, 0xcc, 0xcb, 0x28, 0x4d, 0xd4, 0x03, 0x8b,
	0x08, 0x71, 0xc0, 0x24, 0x94, 0x7a, 0x18, 0xb9, 0xd8, 0x7c, 0xc1, 0x52, 0x42, 0x7c, 0x5c, 0x4c,
	0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x42, 0x5c, 0x2c,
	0xc1, 0x99, 0x25, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17,
	0x9b, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x27,
	0x24, 0xc1, 0xc5, 0xee, 0x9c, 0x91, 0x58, 0x50, 0x92, 0x5a, 0x24, 0xc1, 0x02, 0x56, 0x0e, 0xe3,
	0x0a, 0x89, 0x70, 0xb1, 0x86, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0xb0, 0x82, 0xc5, 0x21, 0x1c, 0x90,
	0x39, 0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0x12, 0x6c, 0x60, 0x61, 0x28, 0x2f, 0x89, 0x0d, 0xec,
	0x30, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x5f, 0x68, 0xe3, 0xba, 0x00, 0x00, 0x00,
}
