// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/parser_article_page.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParserArticlePage struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=Site,proto3" json:"Site,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserArticlePage) Reset()         { *m = ParserArticlePage{} }
func (m *ParserArticlePage) String() string { return proto.CompactTextString(m) }
func (*ParserArticlePage) ProtoMessage()    {}
func (*ParserArticlePage) Descriptor() ([]byte, []int) {
	return fileDescriptor_parser_article_page_0cbc3ecd1d3d1be3, []int{0}
}
func (m *ParserArticlePage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserArticlePage.Unmarshal(m, b)
}
func (m *ParserArticlePage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserArticlePage.Marshal(b, m, deterministic)
}
func (dst *ParserArticlePage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserArticlePage.Merge(dst, src)
}
func (m *ParserArticlePage) XXX_Size() int {
	return xxx_messageInfo_ParserArticlePage.Size(m)
}
func (m *ParserArticlePage) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserArticlePage.DiscardUnknown(m)
}

var xxx_messageInfo_ParserArticlePage proto.InternalMessageInfo

func (m *ParserArticlePage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ParserArticlePage) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ParserArticlePage) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *ParserArticlePage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ParserArticlePage)(nil), "protobuf.Parser_article_page")
}

func init() {
	proto.RegisterFile("protobuf/parser_article_page.proto", fileDescriptor_parser_article_page_0cbc3ecd1d3d1be3)
}

var fileDescriptor_parser_article_page_0cbc3ecd1d3d1be3 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x2c, 0x2a, 0x4e, 0x2d, 0x8a, 0x4f, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x49, 0x8d, 0x2f, 0x48, 0x4c, 0x4f, 0xd5, 0x03, 0x4b, 0x0a, 0x71, 0xc0, 0xd4, 0x28,
	0xa5, 0x73, 0x09, 0x07, 0x60, 0x2a, 0x13, 0xe2, 0xe3, 0x62, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x09, 0x62, 0xf2, 0x4c, 0x11, 0x92, 0xe2, 0xe2, 0x70, 0x4e, 0x2c, 0x49, 0x4d, 0xcf,
	0x2f, 0xaa, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x82,
	0x33, 0x4b, 0x52, 0x25, 0x98, 0xc1, 0xe2, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x68, 0x51, 0x8e,
	0x04, 0x0b, 0x58, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0x5b, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xb1, 0x05, 0x6e, 0x99, 0x9f, 0x00, 0x00, 0x00,
}
