// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/parser_manhua_listing.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParserManhuaListing struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=Site,proto3" json:"Site,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserManhuaListing) Reset()         { *m = ParserManhuaListing{} }
func (m *ParserManhuaListing) String() string { return proto.CompactTextString(m) }
func (*ParserManhuaListing) ProtoMessage()    {}
func (*ParserManhuaListing) Descriptor() ([]byte, []int) {
	return fileDescriptor_parser_manhua_listing_252e38926ab7e0cf, []int{0}
}
func (m *ParserManhuaListing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserManhuaListing.Unmarshal(m, b)
}
func (m *ParserManhuaListing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserManhuaListing.Marshal(b, m, deterministic)
}
func (dst *ParserManhuaListing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserManhuaListing.Merge(dst, src)
}
func (m *ParserManhuaListing) XXX_Size() int {
	return xxx_messageInfo_ParserManhuaListing.Size(m)
}
func (m *ParserManhuaListing) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserManhuaListing.DiscardUnknown(m)
}

var xxx_messageInfo_ParserManhuaListing proto.InternalMessageInfo

func (m *ParserManhuaListing) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ParserManhuaListing) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ParserManhuaListing) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *ParserManhuaListing) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ParserManhuaListing)(nil), "protobuf.Parser_manhua_listing")
}

func init() {
	proto.RegisterFile("protobuf/parser_manhua_listing.proto", fileDescriptor_parser_manhua_listing_252e38926ab7e0cf)
}

var fileDescriptor_parser_manhua_listing_252e38926ab7e0cf = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x2c, 0x2a, 0x4e, 0x2d, 0x8a, 0xcf, 0x4d, 0xcc, 0xcb,
	0x28, 0x4d, 0x8c, 0xcf, 0xc9, 0x2c, 0x2e, 0xc9, 0xcc, 0x4b, 0xd7, 0x03, 0x4b, 0x0b, 0x71, 0xc0,
	0x54, 0x29, 0x65, 0x72, 0x89, 0x06, 0x60, 0x53, 0x28, 0xc4, 0xc7, 0xc5, 0xe4, 0x99, 0x22, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0xc4, 0xe4, 0x99, 0x22, 0x24, 0xc5, 0xc5, 0xe1, 0x9c, 0x58, 0x92,
	0x9a, 0x9e, 0x5f, 0x54, 0x29, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x09, 0x71,
	0xb1, 0x04, 0x67, 0x96, 0xa4, 0x4a, 0x30, 0x83, 0xc5, 0xc1, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xd0,
	0xa2, 0x1c, 0x09, 0x16, 0xb0, 0x10, 0x88, 0x99, 0xc4, 0x06, 0xb6, 0xd4, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xba, 0x71, 0xe7, 0x2f, 0xa3, 0x00, 0x00, 0x00,
}
