// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parser_job.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParserJob struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=Site,proto3" json:"Site,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserJob) Reset()         { *m = ParserJob{} }
func (m *ParserJob) String() string { return proto.CompactTextString(m) }
func (*ParserJob) ProtoMessage()    {}
func (*ParserJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_parser_job_160168fb8aa34e0a, []int{0}
}
func (m *ParserJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserJob.Unmarshal(m, b)
}
func (m *ParserJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserJob.Marshal(b, m, deterministic)
}
func (dst *ParserJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserJob.Merge(dst, src)
}
func (m *ParserJob) XXX_Size() int {
	return xxx_messageInfo_ParserJob.Size(m)
}
func (m *ParserJob) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserJob.DiscardUnknown(m)
}

var xxx_messageInfo_ParserJob proto.InternalMessageInfo

func (m *ParserJob) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ParserJob) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ParserJob) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *ParserJob) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ParserJob)(nil), "protobuf.Parser_job")
}

func init() { proto.RegisterFile("parser_job.proto", fileDescriptor_parser_job_160168fb8aa34e0a) }

var fileDescriptor_parser_job_160168fb8aa34e0a = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0x2c, 0x2a,
	0x4e, 0x2d, 0x8a, 0xcf, 0xca, 0x4f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x49, 0xa5, 0x69, 0x4a, 0x71, 0x5c, 0x5c, 0x01, 0x70, 0x59, 0x21, 0x3e, 0x2e, 0x26, 0xcf, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x26, 0xcf, 0x14, 0x21, 0x29, 0x2e, 0x0e, 0xe7, 0xc4,
	0x92, 0xd4, 0xf4, 0xfc, 0xa2, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48,
	0x88, 0x8b, 0x25, 0x38, 0xb3, 0x24, 0x55, 0x82, 0x19, 0x2c, 0x0e, 0x66, 0x0b, 0x09, 0x70, 0x31,
	0x87, 0x16, 0xe5, 0x48, 0xb0, 0x80, 0x85, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0x4d, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x11, 0x05, 0x3c, 0x23, 0x84, 0x00, 0x00, 0x00,
}
