// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_manhua_image.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaImage struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Site                 *string  `protobuf:"bytes,2,req,name=Site" json:"Site,omitempty"`
	Number               *int32   `protobuf:"varint,3,req,name=Number" json:"Number,omitempty"`
	Chapter              *string  `protobuf:"bytes,4,req,name=Chapter" json:"Chapter,omitempty"`
	Sequence             *string  `protobuf:"bytes,5,req,name=Sequence" json:"Sequence,omitempty"`
	Url                  *string  `protobuf:"bytes,6,req,name=Url" json:"Url,omitempty"`
	Uuid                 *string  `protobuf:"bytes,7,req,name=Uuid" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaverManhuaImage) Reset()         { *m = SaverManhuaImage{} }
func (m *SaverManhuaImage) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaImage) ProtoMessage()    {}
func (*SaverManhuaImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_image_dd7e9922f8914eab, []int{0}
}
func (m *SaverManhuaImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaImage.Unmarshal(m, b)
}
func (m *SaverManhuaImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaImage.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaImage.Merge(dst, src)
}
func (m *SaverManhuaImage) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaImage.Size(m)
}
func (m *SaverManhuaImage) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaImage.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaImage proto.InternalMessageInfo

func (m *SaverManhuaImage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SaverManhuaImage) GetSite() string {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return ""
}

func (m *SaverManhuaImage) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *SaverManhuaImage) GetChapter() string {
	if m != nil && m.Chapter != nil {
		return *m.Chapter
	}
	return ""
}

func (m *SaverManhuaImage) GetSequence() string {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return ""
}

func (m *SaverManhuaImage) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *SaverManhuaImage) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*SaverManhuaImage)(nil), "protobuf.Saver_manhua_image")
}

func init() {
	proto.RegisterFile("protobuf/saver_manhua_image.proto", fileDescriptor_saver_manhua_image_dd7e9922f8914eab)
}

var fileDescriptor_saver_manhua_image_dd7e9922f8914eab = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8d, 0x3d, 0x0e, 0x82, 0x40,
	0x10, 0x46, 0xc3, 0xf2, 0xeb, 0x14, 0xc6, 0x4c, 0x61, 0x26, 0x56, 0x68, 0x45, 0xa5, 0x87, 0xb0,
	0xa2, 0xb1, 0x80, 0x50, 0x93, 0x45, 0x46, 0x21, 0x91, 0x1f, 0x57, 0xd6, 0x53, 0x79, 0x48, 0xb3,
	0xab, 0xd8, 0xd8, 0xbd, 0x37, 0xf3, 0x92, 0x0f, 0xb6, 0xa3, 0x1a, 0xa6, 0xa1, 0xd2, 0x97, 0xc3,
	0x43, 0x3e, 0x59, 0x95, 0x9d, 0xec, 0x1b, 0x2d, 0xcb, 0xb6, 0x93, 0x57, 0xde, 0xdb, 0x1f, 0x46,
	0x73, 0xb2, 0x7b, 0x39, 0x80, 0xf9, 0x5f, 0x86, 0x4b, 0x10, 0x69, 0x4d, 0x4e, 0x2c, 0x12, 0x2f,
	0x13, 0x69, 0x8d, 0x08, 0x5e, 0xde, 0x4e, 0x4c, 0x22, 0x16, 0xc9, 0x22, 0xb3, 0x8c, 0x6b, 0x08,
	0x4e, 0xba, 0xab, 0x58, 0x91, 0x1b, 0x8b, 0xc4, 0xcf, 0xbe, 0x86, 0x04, 0xe1, 0xb1, 0x91, 0xe3,
	0xc4, 0x8a, 0x3c, 0x9b, 0xcf, 0x8a, 0x1b, 0x88, 0x72, 0xbe, 0x6b, 0xee, 0xcf, 0x4c, 0xbe, 0x7d,
	0xfd, 0x1c, 0x57, 0xe0, 0x16, 0xea, 0x46, 0x81, 0x3d, 0x1b, 0x34, 0x9b, 0x85, 0x6e, 0x6b, 0x0a,
	0x3f, 0x9b, 0x86, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x5d, 0x8f, 0x4a, 0xdc, 0x00, 0x00,
	0x00,
}
