// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_participle_count.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverParticipleCount struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:word"
	Word string `protobuf:"bytes,2,opt,name=Word,proto3" json:"Word,omitempty" gorm:"index:word"`
	// @inject_tag: gorm:"index:count"
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty" gorm:"index:count"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *SaverParticipleCount) Reset()         { *m = SaverParticipleCount{} }
func (m *SaverParticipleCount) String() string { return proto.CompactTextString(m) }
func (*SaverParticipleCount) ProtoMessage()    {}
func (*SaverParticipleCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_participle_count_7c2d16e377249eb7, []int{0}
}
func (m *SaverParticipleCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverParticipleCount.Unmarshal(m, b)
}
func (m *SaverParticipleCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverParticipleCount.Marshal(b, m, deterministic)
}
func (dst *SaverParticipleCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverParticipleCount.Merge(dst, src)
}
func (m *SaverParticipleCount) XXX_Size() int {
	return xxx_messageInfo_SaverParticipleCount.Size(m)
}
func (m *SaverParticipleCount) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverParticipleCount.DiscardUnknown(m)
}

var xxx_messageInfo_SaverParticipleCount proto.InternalMessageInfo

func (m *SaverParticipleCount) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverParticipleCount) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *SaverParticipleCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*SaverParticipleCount)(nil), "protobuf.Saver_participle_count")
}

func init() {
	proto.RegisterFile("protobuf/saver_participle_count.proto", fileDescriptor_saver_participle_count_7c2d16e377249eb7)
}

var fileDescriptor_saver_participle_count_7c2d16e377249eb7 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4e, 0x2c, 0x4b, 0x2d, 0x8a, 0x2f, 0x48, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x2c, 0xc8, 0x49, 0x8d, 0x4f, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x03, 0xcb, 0x0b, 0x71,
	0xc0, 0x94, 0x29, 0x05, 0x71, 0x89, 0x05, 0x63, 0x55, 0x29, 0xc4, 0xc7, 0xc5, 0xe4, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0xc4, 0xe4, 0x99, 0x22, 0x24, 0xc4, 0xc5, 0x12, 0x9e, 0x5f,
	0x94, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0x82, 0x15,
	0x4b, 0x30, 0x83, 0x95, 0x41, 0x38, 0x49, 0x6c, 0x60, 0xd3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x59, 0x9b, 0x01, 0x8d, 0x00, 0x00, 0x00,
}
