// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_manhua_chapter.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaChapter struct {
	Id                   *uint64              `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Site                 *string              `protobuf:"bytes,2,req,name=Site" json:"Site,omitempty"`
	Number               *int32               `protobuf:"varint,3,req,name=Number" json:"Number,omitempty"`
	Chapter              *string              `protobuf:"bytes,4,req,name=Chapter" json:"Chapter,omitempty"`
	Title                *string              `protobuf:"bytes,5,req,name=Title" json:"Title,omitempty"`
	Url                  *string              `protobuf:"bytes,6,req,name=Url" json:"Url,omitempty"`
	FinishedTime         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=FinishedTime" json:"FinishedTime,omitempty"`
	Available            *bool                `protobuf:"varint,8,req,name=Available" json:"Available,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=UpdateTime" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SaverManhuaChapter) Reset()         { *m = SaverManhuaChapter{} }
func (m *SaverManhuaChapter) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaChapter) ProtoMessage()    {}
func (*SaverManhuaChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_chapter_2ed15e9d9c743468, []int{0}
}
func (m *SaverManhuaChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaChapter.Unmarshal(m, b)
}
func (m *SaverManhuaChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaChapter.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaChapter.Merge(dst, src)
}
func (m *SaverManhuaChapter) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaChapter.Size(m)
}
func (m *SaverManhuaChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaChapter.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaChapter proto.InternalMessageInfo

func (m *SaverManhuaChapter) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SaverManhuaChapter) GetSite() string {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return ""
}

func (m *SaverManhuaChapter) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *SaverManhuaChapter) GetChapter() string {
	if m != nil && m.Chapter != nil {
		return *m.Chapter
	}
	return ""
}

func (m *SaverManhuaChapter) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *SaverManhuaChapter) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *SaverManhuaChapter) GetFinishedTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedTime
	}
	return nil
}

func (m *SaverManhuaChapter) GetAvailable() bool {
	if m != nil && m.Available != nil {
		return *m.Available
	}
	return false
}

func (m *SaverManhuaChapter) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SaverManhuaChapter)(nil), "task.Saver_manhua_chapter")
}

func init() {
	proto.RegisterFile("protobuf/saver_manhua_chapter.proto", fileDescriptor_saver_manhua_chapter_2ed15e9d9c743468)
}

var fileDescriptor_saver_manhua_chapter_2ed15e9d9c743468 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0xd9, 0x6c, 0xf7, 0x4f, 0x9f, 0x22, 0x12, 0x16, 0x09, 0x8b, 0x87, 0xa2, 0x97, 0x9e,
	0x5a, 0xf0, 0xe8, 0x41, 0x50, 0x41, 0xd8, 0x8b, 0x87, 0x6e, 0xf7, 0xbc, 0xa4, 0xdb, 0x67, 0x1b,
	0x4c, 0x9a, 0x90, 0xa6, 0x05, 0xbf, 0x94, 0x9f, 0x51, 0x4c, 0xad, 0xab, 0x20, 0x78, 0x9b, 0x99,
	0x37, 0xfc, 0x1e, 0x03, 0xd7, 0xc6, 0x6a, 0xa7, 0x8b, 0xee, 0x25, 0x6d, 0x79, 0x8f, 0x76, 0xaf,
	0x78, 0x53, 0x77, 0x7c, 0x7f, 0xa8, 0xb9, 0x71, 0x68, 0x13, 0x7f, 0xa5, 0x81, 0xe3, 0xed, 0xeb,
	0xfa, 0xa1, 0xc7, 0xa6, 0xd4, 0x36, 0xad, 0x84, 0xab, 0xbb, 0x22, 0x39, 0x68, 0x95, 0x56, 0x5a,
	0xf2, 0xa6, 0x4a, 0xbf, 0x19, 0xc6, 0xbd, 0x19, 0x6c, 0x53, 0x27, 0x14, 0xb6, 0x8e, 0x2b, 0x73,
	0x54, 0x03, 0xe9, 0xea, 0x9d, 0xc0, 0x6a, 0xfb, 0xc7, 0x23, 0x7a, 0x06, 0x64, 0x53, 0xb2, 0x49,
	0x44, 0xe2, 0x20, 0x23, 0x9b, 0x92, 0x52, 0x08, 0xb6, 0xc2, 0x21, 0x23, 0x11, 0x89, 0xc3, 0xcc,
	0x6b, 0x7a, 0x01, 0xf3, 0xe7, 0x4e, 0x15, 0x68, 0xd9, 0x34, 0x22, 0xf1, 0x2c, 0xfb, 0x72, 0x94,
	0xc1, 0xe2, 0x71, 0xc0, 0xb0, 0xc0, 0xd7, 0x47, 0x4b, 0x57, 0x30, 0xcb, 0x85, 0x93, 0xc8, 0x66,
	0x3e, 0x1f, 0x0c, 0x3d, 0x87, 0xe9, 0xce, 0x4a, 0x36, 0xf7, 0xd9, 0xa7, 0xa4, 0x77, 0x70, 0xfa,
	0x24, 0x1a, 0xd1, 0xd6, 0x58, 0xe6, 0x42, 0x21, 0x5b, 0x44, 0x93, 0xf8, 0xe4, 0x66, 0x9d, 0x54,
	0x5a, 0x57, 0x12, 0x93, 0x71, 0x5f, 0x92, 0x8f, 0x73, 0xb2, 0x5f, 0x7d, 0x7a, 0x09, 0xe1, 0x7d,
	0xcf, 0x85, 0xe4, 0x85, 0x44, 0xb6, 0x8c, 0x48, 0xbc, 0xcc, 0x8e, 0x01, 0xbd, 0x05, 0xd8, 0x99,
	0x92, 0x3b, 0xf4, 0xec, 0xf0, 0x5f, 0xf6, 0x8f, 0xf6, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0x13, 0xb4, 0x46, 0xa0, 0x01, 0x00, 0x00,
}
