// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_article.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverArticle struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:site,site_num"
	Site string `protobuf:"bytes,2,opt,name=Site,proto3" json:"Site,omitempty" gorm:"index:site,site_num"`
	// @inject_tag: gorm:"index:number,site_num"
	Number string `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty" gorm:"index:number,site_num"`
	Face   string `protobuf:"bytes,4,opt,name=Face,proto3" json:"Face,omitempty"`
	Title  string `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	// @inject_tag: gorm:"column:ZhTitle"
	ZhTitle  string `protobuf:"bytes,6,opt,name=ZhTitle,proto3" json:"ZhTitle,omitempty" gorm:"column:ZhTitle"`
	Url      string `protobuf:"bytes,7,opt,name=Url,proto3" json:"Url,omitempty"`
	Contents string `protobuf:"bytes,8,opt,name=Contents,proto3" json:"Contents,omitempty"`
	// @inject_tag: gorm:"column:ZhContents"
	ZhContents string `protobuf:"bytes,9,opt,name=ZhContents,proto3" json:"ZhContents,omitempty" gorm:"column:ZhContents"`
	Tags       string `protobuf:"bytes,10,opt,name=Tags,proto3" json:"Tags,omitempty"`
	// @inject_tag: gorm:"column:ZhTags"
	ZhTags string `protobuf:"bytes,11,opt,name=ZhTags,proto3" json:"ZhTags,omitempty" gorm:"column:ZhTags"`
	// @inject_tag: gorm:"column:updatetime"
	UpdateTime           int64    `protobuf:"varint,12,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" gorm:"column:updatetime"`
	// @inject_tag: gorm:"-"
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	// @inject_tag: gorm:"-"
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	// @inject_tag: gorm:"-"
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *SaverArticle) Reset()         { *m = SaverArticle{} }
func (m *SaverArticle) String() string { return proto.CompactTextString(m) }
func (*SaverArticle) ProtoMessage()    {}
func (*SaverArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_article_078bad2742ed8eb7, []int{0}
}
func (m *SaverArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverArticle.Unmarshal(m, b)
}
func (m *SaverArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverArticle.Marshal(b, m, deterministic)
}
func (dst *SaverArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverArticle.Merge(dst, src)
}
func (m *SaverArticle) XXX_Size() int {
	return xxx_messageInfo_SaverArticle.Size(m)
}
func (m *SaverArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverArticle.DiscardUnknown(m)
}

var xxx_messageInfo_SaverArticle proto.InternalMessageInfo

func (m *SaverArticle) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverArticle) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SaverArticle) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *SaverArticle) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *SaverArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SaverArticle) GetZhTitle() string {
	if m != nil {
		return m.ZhTitle
	}
	return ""
}

func (m *SaverArticle) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaverArticle) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *SaverArticle) GetZhContents() string {
	if m != nil {
		return m.ZhContents
	}
	return ""
}

func (m *SaverArticle) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *SaverArticle) GetZhTags() string {
	if m != nil {
		return m.ZhTags
	}
	return ""
}

func (m *SaverArticle) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*SaverArticle)(nil), "protobuf.Saver_article")
}

func init() {
	proto.RegisterFile("protobuf/saver_article.proto", fileDescriptor_saver_article_078bad2742ed8eb7)
}

var fileDescriptor_saver_article_078bad2742ed8eb7 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xc9, 0x26, 0x4d, 0xd3, 0xf1, 0x0f, 0x32, 0x88, 0x0c, 0x22, 0x12, 0x3c, 0xe5, 0xa4,
	0x07, 0x1f, 0x41, 0x10, 0x7a, 0xf1, 0x90, 0xa6, 0x97, 0x5c, 0x64, 0xd3, 0x8c, 0x66, 0x21, 0x6d,
	0xca, 0x66, 0xeb, 0x3b, 0xf9, 0x96, 0xb2, 0xb3, 0x36, 0xe4, 0xf6, 0xfd, 0x7e, 0xf3, 0xb1, 0x7c,
	0x2c, 0x3c, 0x1c, 0xed, 0xe0, 0x86, 0xe6, 0xf4, 0xf5, 0x32, 0xea, 0x1f, 0xb6, 0x9f, 0xda, 0x3a,
	0xb3, 0xeb, 0xf9, 0x59, 0x34, 0x66, 0xe7, 0xeb, 0xd3, 0xaf, 0x82, 0xab, 0xcd, 0xbc, 0x81, 0xd7,
	0xa0, 0xd6, 0x2d, 0x45, 0x79, 0x54, 0x24, 0xa5, 0x5a, 0xb7, 0x88, 0x90, 0x6c, 0x8c, 0x63, 0x52,
	0x79, 0x54, 0xac, 0x4a, 0xc9, 0x78, 0x07, 0xe9, 0xc7, 0x69, 0xdf, 0xb0, 0xa5, 0x58, 0xec, 0x3f,
	0xf9, 0xee, 0xbb, 0xde, 0x31, 0x25, 0xa1, 0xeb, 0x33, 0xde, 0xc2, 0xa2, 0x32, 0xae, 0x67, 0x5a,
	0x88, 0x0c, 0x80, 0x04, 0xcb, 0xba, 0x0b, 0x3e, 0x15, 0x7f, 0x46, 0xbc, 0x81, 0x78, 0x6b, 0x7b,
	0x5a, 0x8a, 0xf5, 0x11, 0xef, 0x21, 0x7b, 0x1b, 0x0e, 0x8e, 0x0f, 0x6e, 0xa4, 0x4c, 0xf4, 0xc4,
	0xf8, 0x08, 0x50, 0x77, 0xd3, 0x75, 0x25, 0xd7, 0x99, 0xf1, 0x8b, 0x2a, 0xfd, 0x3d, 0x12, 0x84,
	0x45, 0x3e, 0xfb, 0xf5, 0x75, 0x27, 0xf6, 0x22, 0xac, 0x0f, 0xe4, 0xdf, 0xda, 0x1e, 0x5b, 0xed,
	0xb8, 0x32, 0x7b, 0xa6, 0xcb, 0x3c, 0x2a, 0xe2, 0x72, 0x66, 0x9a, 0x54, 0x7e, 0xed, 0xf5, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0xc8, 0x16, 0xf9, 0x5c, 0x01, 0x00, 0x00,
}
