// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_participle_group.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverParticipleGroup struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:name"
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"index:name"`
	Word                 string   `protobuf:"bytes,3,opt,name=Word,proto3" json:"Word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *SaverParticipleGroup) Reset()         { *m = SaverParticipleGroup{} }
func (m *SaverParticipleGroup) String() string { return proto.CompactTextString(m) }
func (*SaverParticipleGroup) ProtoMessage()    {}
func (*SaverParticipleGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_participle_group_edeaa76e6600b521, []int{0}
}
func (m *SaverParticipleGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverParticipleGroup.Unmarshal(m, b)
}
func (m *SaverParticipleGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverParticipleGroup.Marshal(b, m, deterministic)
}
func (dst *SaverParticipleGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverParticipleGroup.Merge(dst, src)
}
func (m *SaverParticipleGroup) XXX_Size() int {
	return xxx_messageInfo_SaverParticipleGroup.Size(m)
}
func (m *SaverParticipleGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverParticipleGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SaverParticipleGroup proto.InternalMessageInfo

func (m *SaverParticipleGroup) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverParticipleGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaverParticipleGroup) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func init() {
	proto.RegisterType((*SaverParticipleGroup)(nil), "protobuf.Saver_participle_group")
}

func init() {
	proto.RegisterFile("protobuf/saver_participle_group.proto", fileDescriptor_saver_participle_group_edeaa76e6600b521)
}

var fileDescriptor_saver_participle_group_edeaa76e6600b521 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4e, 0x2c, 0x4b, 0x2d, 0x8a, 0x2f, 0x48, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x2c, 0xc8, 0x49, 0x8d, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x03, 0xcb, 0x0b, 0x71,
	0xc0, 0x94, 0x29, 0x05, 0x70, 0x89, 0x05, 0x63, 0x55, 0x29, 0xc4, 0xc7, 0xc5, 0xe4, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0xc4, 0xe4, 0x99, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98,
	0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0xc2, 0xf3, 0x8b, 0x52,
	0x24, 0x98, 0x21, 0x62, 0x20, 0x76, 0x12, 0x1b, 0xd8, 0x6c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb2, 0xd6, 0x16, 0xa9, 0x8b, 0x00, 0x00, 0x00,
}
