// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/task/saver_manhua_site.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaSite struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Site                 string               `protobuf:"bytes,2,opt,name=Site" json:"Site,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Url                  string               `protobuf:"bytes,4,opt,name=Url" json:"Url,omitempty"`
	Number               int32                `protobuf:"varint,5,opt,name=Number" json:"Number,omitempty"`
	Categories           string               `protobuf:"bytes,6,opt,name=Categories" json:"Categories,omitempty"`
	Face                 string               `protobuf:"bytes,7,opt,name=Face" json:"Face,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=UpdateTime" json:"UpdateTime,omitempty"`
	CheckTime            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=CheckTime" json:"CheckTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SaverManhuaSite) Reset()         { *m = SaverManhuaSite{} }
func (m *SaverManhuaSite) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaSite) ProtoMessage()    {}
func (*SaverManhuaSite) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_site_7976055b2a5f3c61, []int{0}
}
func (m *SaverManhuaSite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaSite.Unmarshal(m, b)
}
func (m *SaverManhuaSite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaSite.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaSite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaSite.Merge(dst, src)
}
func (m *SaverManhuaSite) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaSite.Size(m)
}
func (m *SaverManhuaSite) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaSite.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaSite proto.InternalMessageInfo

func (m *SaverManhuaSite) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverManhuaSite) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SaverManhuaSite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaverManhuaSite) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaverManhuaSite) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SaverManhuaSite) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

func (m *SaverManhuaSite) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *SaverManhuaSite) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *SaverManhuaSite) GetCheckTime() *timestamp.Timestamp {
	if m != nil {
		return m.CheckTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SaverManhuaSite)(nil), "task.Saver_manhua_site")
}

func init() {
	proto.RegisterFile("protobuf/task/saver_manhua_site.proto", fileDescriptor_saver_manhua_site_7976055b2a5f3c61)
}

var fileDescriptor_saver_manhua_site_7976055b2a5f3c61 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xc3, 0x30,
	0x1c, 0xc7, 0x69, 0xd7, 0x55, 0x1b, 0x41, 0x34, 0x07, 0x09, 0x3b, 0x48, 0x11, 0x84, 0x9e, 0x1a,
	0xd0, 0x8b, 0x78, 0x74, 0x20, 0xec, 0xb2, 0x43, 0xb7, 0x9d, 0x47, 0xda, 0xfe, 0x96, 0x86, 0x35,
	0x4d, 0x49, 0xd2, 0x81, 0x4f, 0xe3, 0xab, 0x4a, 0xd2, 0xe9, 0x86, 0x97, 0xdd, 0x3e, 0xf9, 0xfe,
	0x0b, 0x09, 0x7a, 0xee, 0xb5, 0xb2, 0xaa, 0x1c, 0x76, 0xd4, 0x32, 0xb3, 0xa7, 0x86, 0x1d, 0x40,
	0x6f, 0x25, 0xeb, 0x9a, 0x81, 0x6d, 0x8d, 0xb0, 0x90, 0x7b, 0x1f, 0x47, 0xce, 0x9d, 0x7d, 0x1c,
	0xa0, 0xab, 0x95, 0xa6, 0x5c, 0xd8, 0x66, 0x28, 0xf3, 0x4a, 0x49, 0xca, 0x55, 0xcb, 0x3a, 0x4e,
	0xff, 0x56, 0x7a, 0xfb, 0xd5, 0x83, 0xa1, 0x56, 0x48, 0x30, 0x96, 0xc9, 0xfe, 0x44, 0xe3, 0xd2,
	0xd3, 0x77, 0x88, 0xee, 0x57, 0xff, 0x6f, 0xc1, 0xb7, 0x28, 0x5c, 0xd4, 0x24, 0x48, 0x83, 0x2c,
	0x2a, 0xc2, 0x45, 0x8d, 0x31, 0x8a, 0x56, 0xc2, 0x02, 0x09, 0xd3, 0x20, 0x4b, 0x0a, 0xcf, 0x4e,
	0x5b, 0x32, 0x09, 0x64, 0x32, 0x6a, 0x8e, 0xf1, 0x1d, 0x9a, 0x6c, 0x74, 0x4b, 0x22, 0x2f, 0x39,
	0xc4, 0x0f, 0x28, 0x5e, 0x0e, 0xb2, 0x04, 0x4d, 0xa6, 0x69, 0x90, 0x4d, 0x8b, 0xe3, 0x09, 0x3f,
	0x22, 0x34, 0x67, 0x16, 0xb8, 0xd2, 0x02, 0x0c, 0x89, 0x7d, 0xe1, 0x4c, 0x71, 0xeb, 0x9f, 0xac,
	0x02, 0x72, 0x35, 0xae, 0x3b, 0xc6, 0xef, 0x08, 0x6d, 0xfa, 0x9a, 0x59, 0x58, 0x0b, 0x09, 0xe4,
	0x3a, 0x0d, 0xb2, 0x9b, 0x97, 0x59, 0xce, 0x95, 0xe2, 0xed, 0xf1, 0x63, 0xca, 0x61, 0x97, 0xaf,
	0x7f, 0x5f, 0x58, 0x9c, 0xa5, 0xf1, 0x1b, 0x4a, 0xe6, 0x0d, 0x54, 0x7b, 0x5f, 0x4d, 0x2e, 0x56,
	0x4f, 0xe1, 0x32, 0xf6, 0xf6, 0xeb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xfa, 0xc1, 0x8a,
	0x9b, 0x01, 0x00, 0x00,
}
