// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_manhua_book.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaBook struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:site"
	Site string `protobuf:"bytes,2,opt,name=Site" json:"Site,omitempty" gorm:"index:site"`
	Name string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Url  string `protobuf:"bytes,4,opt,name=Url" json:"Url,omitempty"`
	// @inject_tag: gorm:"index:number"
	Number      int32  `protobuf:"varint,5,opt,name=Number" json:"Number,omitempty" gorm:"index:number"`
	Categories  string `protobuf:"bytes,6,opt,name=Categories" json:"Categories,omitempty"`
	Description string `protobuf:"bytes,7,opt,name=Description" json:"Description,omitempty"`
	Face        string `protobuf:"bytes,8,opt,name=Face" json:"Face,omitempty"`
	// @inject_tag: gorm:"column:UpdateTime"
	UpdateTime int64 `protobuf:"varint,9,opt,name=UpdateTime" json:"UpdateTime,omitempty" gorm:"column:UpdateTime"`
	// @inject_tag: gorm:"column:CheckTime"
	CheckTime            int64    `protobuf:"varint,10,opt,name=CheckTime" json:"CheckTime,omitempty" gorm:"column:CheckTime"`
	// @inject_tag: gorm:"-"
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	// @inject_tag: gorm:"-"
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	// @inject_tag: gorm:"-"
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *SaverManhuaBook) Reset()         { *m = SaverManhuaBook{} }
func (m *SaverManhuaBook) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaBook) ProtoMessage()    {}
func (*SaverManhuaBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_book_e897c4ab660f056b, []int{0}
}
func (m *SaverManhuaBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaBook.Unmarshal(m, b)
}
func (m *SaverManhuaBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaBook.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaBook.Merge(dst, src)
}
func (m *SaverManhuaBook) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaBook.Size(m)
}
func (m *SaverManhuaBook) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaBook.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaBook proto.InternalMessageInfo

func (m *SaverManhuaBook) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverManhuaBook) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SaverManhuaBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaverManhuaBook) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaverManhuaBook) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SaverManhuaBook) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

func (m *SaverManhuaBook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SaverManhuaBook) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *SaverManhuaBook) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SaverManhuaBook) GetCheckTime() int64 {
	if m != nil {
		return m.CheckTime
	}
	return 0
}

func init() {
	proto.RegisterType((*SaverManhuaBook)(nil), "protobuf.Saver_manhua_book")
}

func init() {
	proto.RegisterFile("protobuf/saver_manhua_book.proto", fileDescriptor_saver_manhua_book_e897c4ab660f056b)
}

var fileDescriptor_saver_manhua_book_e897c4ab660f056b = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x24, 0x0d, 0xcd, 0x21, 0x21, 0xb8, 0x01, 0xdd, 0x80, 0x90, 0xc5, 0x94, 0x09,
	0x06, 0x1e, 0xa1, 0x08, 0xa9, 0x4b, 0x87, 0x94, 0xce, 0x95, 0x93, 0x1c, 0xd4, 0x2a, 0xa9, 0x23,
	0xc7, 0xe1, 0x1d, 0x78, 0x6b, 0xe4, 0x0b, 0x88, 0xa8, 0xdb, 0xe7, 0xef, 0xff, 0xed, 0x5f, 0x32,
	0xe8, 0xde, 0xbb, 0xe0, 0xea, 0xf1, 0xfd, 0x69, 0x30, 0x5f, 0xec, 0xf7, 0x9d, 0x39, 0x1d, 0x46,
	0xb3, 0xaf, 0x9d, 0x3b, 0x3e, 0x4a, 0x84, 0xcb, 0xbf, 0xc6, 0xc3, 0x77, 0x02, 0x37, 0xdb, 0xf3,
	0x16, 0x5e, 0x41, 0xb2, 0x6e, 0x49, 0x69, 0x55, 0x66, 0x55, 0xb2, 0x6e, 0x11, 0x21, 0xdb, 0xda,
	0xc0, 0x94, 0x68, 0x55, 0x16, 0x95, 0x70, 0x74, 0x1b, 0xd3, 0x31, 0xa5, 0x93, 0x8b, 0x8c, 0xd7,
	0x90, 0xee, 0xfc, 0x27, 0x65, 0xa2, 0x22, 0xe2, 0x2d, 0xe4, 0x9b, 0xb1, 0xab, 0xd9, 0xd3, 0x42,
	0xab, 0x72, 0x51, 0xfd, 0x9e, 0xf0, 0x1e, 0x60, 0x65, 0x02, 0x7f, 0x38, 0x6f, 0x79, 0xa0, 0x5c,
	0x2e, 0xcc, 0x0c, 0x6a, 0xb8, 0x7c, 0xe1, 0xa1, 0xf1, 0xb6, 0x0f, 0xd6, 0x9d, 0xe8, 0x42, 0x0a,
	0x73, 0x15, 0xf7, 0x5f, 0x4d, 0xc3, 0xb4, 0x9c, 0xf6, 0x23, 0xc7, 0x57, 0x77, 0x7d, 0x6b, 0x02,
	0xbf, 0xd9, 0x8e, 0xa9, 0xd0, 0xaa, 0x4c, 0xab, 0x99, 0xc1, 0x3b, 0x28, 0x56, 0x07, 0x6e, 0x8e,
	0x12, 0x83, 0xc4, 0xff, 0xa2, 0xce, 0xe5, 0x57, 0x9e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe1,
	0xce, 0x2a, 0x2e, 0x40, 0x01, 0x00, 0x00,
}
