// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/task/saver_manhua_chapter.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaChapter struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Site                 string               `protobuf:"bytes,2,opt,name=Site" json:"Site,omitempty"`
	Number               int32                `protobuf:"varint,3,opt,name=Number" json:"Number,omitempty"`
	Chapter              string               `protobuf:"bytes,4,opt,name=Chapter" json:"Chapter,omitempty"`
	Title                string               `protobuf:"bytes,5,opt,name=Title" json:"Title,omitempty"`
	Url                  string               `protobuf:"bytes,6,opt,name=Url" json:"Url,omitempty"`
	FinishedTime         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=FinishedTime" json:"FinishedTime,omitempty"`
	Available            bool                 `protobuf:"varint,8,opt,name=Available" json:"Available,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=UpdateTime" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SaverManhuaChapter) Reset()         { *m = SaverManhuaChapter{} }
func (m *SaverManhuaChapter) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaChapter) ProtoMessage()    {}
func (*SaverManhuaChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_chapter_eb3c28ae87150325, []int{0}
}
func (m *SaverManhuaChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaChapter.Unmarshal(m, b)
}
func (m *SaverManhuaChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaChapter.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaChapter.Merge(dst, src)
}
func (m *SaverManhuaChapter) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaChapter.Size(m)
}
func (m *SaverManhuaChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaChapter.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaChapter proto.InternalMessageInfo

func (m *SaverManhuaChapter) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverManhuaChapter) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SaverManhuaChapter) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SaverManhuaChapter) GetChapter() string {
	if m != nil {
		return m.Chapter
	}
	return ""
}

func (m *SaverManhuaChapter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SaverManhuaChapter) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaverManhuaChapter) GetFinishedTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedTime
	}
	return nil
}

func (m *SaverManhuaChapter) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *SaverManhuaChapter) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SaverManhuaChapter)(nil), "task.Saver_manhua_chapter")
}

func init() {
	proto.RegisterFile("protobuf/task/saver_manhua_chapter.proto", fileDescriptor_saver_manhua_chapter_eb3c28ae87150325)
}

var fileDescriptor_saver_manhua_chapter_eb3c28ae87150325 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x4d, 0x4b, 0x33, 0x31,
	0x14, 0x85, 0xc9, 0x74, 0xfa, 0x75, 0xdf, 0x17, 0x91, 0x50, 0x24, 0x14, 0x17, 0x83, 0xab, 0xac,
	0x26, 0xa0, 0x3b, 0x17, 0x82, 0x0a, 0x42, 0x37, 0x2e, 0xa6, 0xed, 0xba, 0x64, 0x3a, 0xd7, 0x99,
	0x60, 0x32, 0x09, 0x99, 0x4c, 0xc1, 0x3f, 0xe5, 0x6f, 0x94, 0xa6, 0xd6, 0x2a, 0x08, 0xee, 0xce,
	0x39, 0x79, 0x78, 0xc2, 0x05, 0xee, 0xbc, 0x0d, 0xb6, 0xec, 0x5f, 0x44, 0x90, 0xdd, 0xab, 0xe8,
	0xe4, 0x0e, 0xfd, 0xc6, 0xc8, 0xb6, 0xe9, 0xe5, 0x66, 0xdb, 0x48, 0x17, 0xd0, 0xe7, 0x11, 0xa1,
	0xe9, 0x1e, 0x98, 0x3f, 0xec, 0xb0, 0xad, 0xac, 0x17, 0xb5, 0x0a, 0x4d, 0x5f, 0xe6, 0x5b, 0x6b,
	0x44, 0x6d, 0xb5, 0x6c, 0x6b, 0xf1, 0x25, 0x72, 0xe1, 0xcd, 0x61, 0x27, 0x82, 0x32, 0xd8, 0x05,
	0x69, 0xdc, 0x29, 0x1d, 0x4c, 0x57, 0xef, 0x09, 0xcc, 0x96, 0xbf, 0x7c, 0x44, 0xcf, 0x20, 0x59,
	0x54, 0x8c, 0x64, 0x84, 0xa7, 0x45, 0xb2, 0xa8, 0x28, 0x85, 0x74, 0xa9, 0x02, 0xb2, 0x24, 0x23,
	0x7c, 0x5a, 0xc4, 0x4c, 0x2f, 0x60, 0xf4, 0xdc, 0x9b, 0x12, 0x3d, 0x1b, 0x64, 0x84, 0x0f, 0x8b,
	0xcf, 0x46, 0x19, 0x8c, 0x1f, 0x0f, 0x1a, 0x96, 0x46, 0xfc, 0x58, 0xe9, 0x0c, 0x86, 0x2b, 0x15,
	0x34, 0xb2, 0x61, 0xdc, 0x0f, 0x85, 0x9e, 0xc3, 0x60, 0xed, 0x35, 0x1b, 0xc5, 0x6d, 0x1f, 0xe9,
	0x1d, 0xfc, 0x7f, 0x52, 0xad, 0xea, 0x1a, 0xac, 0x56, 0xca, 0x20, 0x1b, 0x67, 0x84, 0xff, 0xbb,
	0x9e, 0xe7, 0xb5, 0xb5, 0xb5, 0xc6, 0xfc, 0x78, 0x5f, 0xbe, 0x3a, 0x9e, 0x53, 0xfc, 0xe0, 0xe9,
	0x25, 0x4c, 0xef, 0x77, 0x52, 0x69, 0x59, 0x6a, 0x64, 0x93, 0x8c, 0xf0, 0x49, 0x71, 0x1a, 0xe8,
	0x2d, 0xc0, 0xda, 0x55, 0x32, 0x60, 0x74, 0x4f, 0xff, 0x74, 0x7f, 0xa3, 0xcb, 0x51, 0x7c, 0xbf,
	0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xc3, 0x14, 0x13, 0xad, 0x01, 0x00, 0x00,
}
