// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_article.proto

package protobuf

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverArticle struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// @inject_tag: gorm:"index:site,site_num"
	Site string `protobuf:"bytes,2,opt,name=Site,proto3" json:"Site,omitempty" gorm:"index:site,site_num"`
	// @inject_tag: gorm:"index:number,site_num"
	Number     int32  `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty" gorm:"index:number,site_num"`
	Title      string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	ZhTitle    string `protobuf:"bytes,5,opt,name=ZhTitle,proto3" json:"ZhTitle,omitempty"`
	Url        string `protobuf:"bytes,6,opt,name=Url,proto3" json:"Url,omitempty"`
	Contents   string `protobuf:"bytes,7,opt,name=Contents,proto3" json:"Contents,omitempty"`
	ZhContents string `protobuf:"bytes,8,opt,name=ZhContents,proto3" json:"ZhContents,omitempty"`
	Face       string `protobuf:"bytes,9,opt,name=Face,proto3" json:"Face,omitempty"`
	// @inject_tag: gorm:"column:UpdateTime"
	UpdateTime           int64    `protobuf:"varint,10,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" gorm:"column:UpdateTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-"`
}

func (m *SaverArticle) Reset()         { *m = SaverArticle{} }
func (m *SaverArticle) String() string { return proto.CompactTextString(m) }
func (*SaverArticle) ProtoMessage()    {}
func (*SaverArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_article_b2afa84b69b4d4c9, []int{0}
}
func (m *SaverArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverArticle.Unmarshal(m, b)
}
func (m *SaverArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverArticle.Marshal(b, m, deterministic)
}
func (dst *SaverArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverArticle.Merge(dst, src)
}
func (m *SaverArticle) XXX_Size() int {
	return xxx_messageInfo_SaverArticle.Size(m)
}
func (m *SaverArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverArticle.DiscardUnknown(m)
}

var xxx_messageInfo_SaverArticle proto.InternalMessageInfo

func (m *SaverArticle) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaverArticle) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SaverArticle) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SaverArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SaverArticle) GetZhTitle() string {
	if m != nil {
		return m.ZhTitle
	}
	return ""
}

func (m *SaverArticle) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaverArticle) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *SaverArticle) GetZhContents() string {
	if m != nil {
		return m.ZhContents
	}
	return ""
}

func (m *SaverArticle) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *SaverArticle) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*SaverArticle)(nil), "protobuf.Saver_article")
}

func init() {
	proto.RegisterFile("protobuf/saver_article.proto", fileDescriptor_saver_article_b2afa84b69b4d4c9)
}

var fileDescriptor_saver_article_b2afa84b69b4d4c9 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xc9, 0xfe, 0xeb, 0x76, 0x40, 0x91, 0x41, 0x64, 0x10, 0x91, 0xe0, 0x29, 0x27, 0x3d,
	0xf8, 0x11, 0x04, 0xa1, 0x17, 0x0f, 0x69, 0x7b, 0xe9, 0x45, 0xb2, 0xdd, 0x91, 0x06, 0xb6, 0xdd,
	0x92, 0xa6, 0x7e, 0x7b, 0x41, 0x32, 0xdb, 0x2e, 0x7b, 0x7b, 0xbf, 0xdf, 0x9b, 0xc0, 0x23, 0xf0,
	0x74, 0x0c, 0x7d, 0xec, 0x9b, 0xf3, 0xcf, 0xdb, 0xc9, 0xfd, 0x72, 0xf8, 0x76, 0x21, 0xfa, 0x6d,
	0xc7, 0xaf, 0xa2, 0xb1, 0xbe, 0xb6, 0x2f, 0x7f, 0x0a, 0x6e, 0x96, 0xd3, 0x0b, 0xbc, 0x85, 0x6c,
	0xd1, 0x92, 0xd2, 0xca, 0x14, 0x36, 0x5b, 0xb4, 0x88, 0x50, 0x2c, 0x7d, 0x64, 0xca, 0xb4, 0x32,
	0x73, 0x2b, 0x19, 0x1f, 0xa0, 0xfa, 0x3a, 0xef, 0x1b, 0x0e, 0x94, 0x6b, 0x65, 0x4a, 0x7b, 0x21,
	0xbc, 0x87, 0x72, 0xe5, 0x63, 0xc7, 0x54, 0xc8, 0xf1, 0x00, 0x48, 0x30, 0xdb, 0xec, 0x06, 0x5f,
	0x8a, 0xbf, 0x22, 0xde, 0x41, 0xbe, 0x0e, 0x1d, 0x55, 0x62, 0x53, 0xc4, 0x47, 0xa8, 0x3f, 0xfa,
	0x43, 0xe4, 0x43, 0x3c, 0xd1, 0x4c, 0xf4, 0xc8, 0xf8, 0x0c, 0xb0, 0xd9, 0x8d, 0x6d, 0x2d, 0xed,
	0xc4, 0xa4, 0xa5, 0x9f, 0x6e, 0xcb, 0x34, 0x1f, 0x96, 0xa6, 0x9c, 0xde, 0xac, 0x8f, 0xad, 0x8b,
	0xbc, 0xf2, 0x7b, 0x26, 0xd0, 0xca, 0xe4, 0x76, 0x62, 0x9a, 0x4a, 0x7e, 0xe2, 0xfd, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x24, 0x04, 0xd5, 0xe5, 0x30, 0x01, 0x00, 0x00,
}
