// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/saver_manhua_site.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaverManhuaSite struct {
	Id                   *uint64              `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Site                 *string              `protobuf:"bytes,2,req,name=Site" json:"Site,omitempty"`
	Name                 *string              `protobuf:"bytes,3,req,name=Name" json:"Name,omitempty"`
	Url                  *string              `protobuf:"bytes,4,req,name=Url" json:"Url,omitempty"`
	Number               *int32               `protobuf:"varint,5,req,name=Number" json:"Number,omitempty"`
	Categories           *string              `protobuf:"bytes,6,req,name=Categories" json:"Categories,omitempty"`
	Face                 *string              `protobuf:"bytes,7,req,name=Face" json:"Face,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=UpdateTime" json:"UpdateTime,omitempty"`
	CheckTime            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=CheckTime" json:"CheckTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SaverManhuaSite) Reset()         { *m = SaverManhuaSite{} }
func (m *SaverManhuaSite) String() string { return proto.CompactTextString(m) }
func (*SaverManhuaSite) ProtoMessage()    {}
func (*SaverManhuaSite) Descriptor() ([]byte, []int) {
	return fileDescriptor_saver_manhua_site_560d9a933f9fe7db, []int{0}
}
func (m *SaverManhuaSite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaverManhuaSite.Unmarshal(m, b)
}
func (m *SaverManhuaSite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaverManhuaSite.Marshal(b, m, deterministic)
}
func (dst *SaverManhuaSite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaverManhuaSite.Merge(dst, src)
}
func (m *SaverManhuaSite) XXX_Size() int {
	return xxx_messageInfo_SaverManhuaSite.Size(m)
}
func (m *SaverManhuaSite) XXX_DiscardUnknown() {
	xxx_messageInfo_SaverManhuaSite.DiscardUnknown(m)
}

var xxx_messageInfo_SaverManhuaSite proto.InternalMessageInfo

func (m *SaverManhuaSite) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SaverManhuaSite) GetSite() string {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return ""
}

func (m *SaverManhuaSite) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SaverManhuaSite) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *SaverManhuaSite) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *SaverManhuaSite) GetCategories() string {
	if m != nil && m.Categories != nil {
		return *m.Categories
	}
	return ""
}

func (m *SaverManhuaSite) GetFace() string {
	if m != nil && m.Face != nil {
		return *m.Face
	}
	return ""
}

func (m *SaverManhuaSite) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *SaverManhuaSite) GetCheckTime() *timestamp.Timestamp {
	if m != nil {
		return m.CheckTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SaverManhuaSite)(nil), "task.Saver_manhua_site")
}

func init() {
	proto.RegisterFile("protobuf/saver_manhua_site.proto", fileDescriptor_saver_manhua_site_560d9a933f9fe7db)
}

var fileDescriptor_saver_manhua_site_560d9a933f9fe7db = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x6b, 0xf3, 0x30,
	0x10, 0x86, 0x89, 0xe2, 0xe4, 0xfb, 0x7c, 0x85, 0xd2, 0x6a, 0x28, 0x22, 0x43, 0x31, 0x9d, 0x3c,
	0xd9, 0xd0, 0xa9, 0x74, 0x6c, 0xa0, 0x90, 0x25, 0x83, 0x93, 0xcc, 0x41, 0xb6, 0x2f, 0xb2, 0x88,
	0x65, 0x19, 0xe9, 0x1c, 0xe8, 0xaf, 0xe9, 0x5f, 0x2d, 0xb6, 0xd3, 0x26, 0x74, 0xe9, 0xf6, 0xe8,
	0xd5, 0xbd, 0x8f, 0xd0, 0x41, 0xd4, 0x3a, 0x4b, 0x36, 0xef, 0x0e, 0xa9, 0x97, 0x27, 0x74, 0x7b,
	0x23, 0x9b, 0xaa, 0x93, 0x7b, 0xaf, 0x09, 0x93, 0xe1, 0x8a, 0x07, 0x24, 0xfd, 0x71, 0xf1, 0x76,
	0xc2, 0xa6, 0xb4, 0x2e, 0x55, 0x9a, 0xaa, 0x2e, 0x4f, 0x0a, 0x6b, 0x52, 0x65, 0x6b, 0xd9, 0xa8,
	0xf4, 0x47, 0xd0, 0xd2, 0x47, 0x8b, 0x3e, 0x25, 0x6d, 0xd0, 0x93, 0x34, 0xed, 0x85, 0x46, 0xd3,
	0xd3, 0x27, 0x83, 0xfb, 0xcd, 0xef, 0x57, 0xf8, 0x2d, 0xb0, 0x55, 0x29, 0x26, 0x11, 0x8b, 0x83,
	0x8c, 0xad, 0x4a, 0xce, 0x21, 0xd8, 0x68, 0x42, 0xc1, 0x22, 0x16, 0x87, 0xd9, 0xc0, 0x7d, 0xb6,
	0x96, 0x06, 0xc5, 0x74, 0xcc, 0x7a, 0xe6, 0x77, 0x30, 0xdd, 0xb9, 0x5a, 0x04, 0x43, 0xd4, 0x23,
	0x7f, 0x80, 0xf9, 0xba, 0x33, 0x39, 0x3a, 0x31, 0x8b, 0x58, 0x3c, 0xcb, 0xce, 0x27, 0xfe, 0x08,
	0xb0, 0x94, 0x84, 0xca, 0x3a, 0x8d, 0x5e, 0xcc, 0x87, 0xc2, 0x55, 0xd2, 0xdb, 0xdf, 0x65, 0x81,
	0xe2, 0xdf, 0x68, 0xef, 0x99, 0xbf, 0x02, 0xec, 0xda, 0x52, 0x12, 0x6e, 0xb5, 0x41, 0xf1, 0x3f,
	0x9a, 0xc4, 0x37, 0xcf, 0x8b, 0x44, 0x59, 0xab, 0xea, 0xf3, 0x62, 0xf2, 0xee, 0x90, 0x6c, 0xbf,
	0x7f, 0x98, 0x5d, 0x4d, 0xf3, 0x17, 0x08, 0x97, 0x15, 0x16, 0xc7, 0xa1, 0x1a, 0xfe, 0x59, 0xbd,
	0x0c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x00, 0x38, 0xe6, 0x00, 0x8e, 0x01, 0x00, 0x00,
}
