// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/task_url.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskUrl struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=Site,proto3" json:"Site,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUrl) Reset()         { *m = TaskUrl{} }
func (m *TaskUrl) String() string { return proto.CompactTextString(m) }
func (*TaskUrl) ProtoMessage()    {}
func (*TaskUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_url_de55ad59340a927a, []int{0}
}
func (m *TaskUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUrl.Unmarshal(m, b)
}
func (m *TaskUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUrl.Marshal(b, m, deterministic)
}
func (dst *TaskUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUrl.Merge(dst, src)
}
func (m *TaskUrl) XXX_Size() int {
	return xxx_messageInfo_TaskUrl.Size(m)
}
func (m *TaskUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUrl.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUrl proto.InternalMessageInfo

func (m *TaskUrl) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskUrl) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *TaskUrl) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *TaskUrl) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskUrl)(nil), "protobuf.Task_url")
}

func init() { proto.RegisterFile("protobuf/task_url.proto", fileDescriptor_task_url_de55ad59340a927a) }

var fileDescriptor_task_url_de55ad59340a927a = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x49, 0x2c, 0xce, 0x8e, 0x2f, 0x2d, 0xca, 0xd1, 0x03, 0x8b,
	0x08, 0x71, 0xc0, 0x24, 0x94, 0x62, 0xb8, 0x38, 0x42, 0xa0, 0x72, 0x42, 0x7c, 0x5c, 0x4c, 0x9e,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x52, 0x5c, 0x1c, 0xce,
	0x89, 0x25, 0xa9, 0xe9, 0xf9, 0x45, 0x95, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe,
	0x90, 0x10, 0x17, 0x4b, 0x70, 0x66, 0x49, 0xaa, 0x04, 0x33, 0x58, 0x1c, 0xcc, 0x16, 0x12, 0xe0,
	0x62, 0x0e, 0x2d, 0xca, 0x91, 0x60, 0x01, 0x0b, 0x81, 0x98, 0x49, 0x6c, 0x60, 0x7b, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xe1, 0xbc, 0xca, 0x89, 0x00, 0x00, 0x00,
}
