// Code generated by protoc-gen-go. DO NOT EDIT.
// source: elasticsearch/m_manhua.proto

package elasticsearch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Manhua struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Site                 string   `protobuf:"bytes,2,opt,name=Site" json:"Site,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=Number" json:"Number,omitempty"`
	Chapter              string   `protobuf:"bytes,4,opt,name=Chapter" json:"Chapter,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title" json:"Title,omitempty"`
	Update               string   `protobuf:"bytes,6,opt,name=Update" json:"Update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manhua) Reset()         { *m = Manhua{} }
func (m *Manhua) String() string { return proto.CompactTextString(m) }
func (*Manhua) ProtoMessage()    {}
func (*Manhua) Descriptor() ([]byte, []int) {
	return fileDescriptor_m_manhua_1f18ee04dbaec3ce, []int{0}
}
func (m *Manhua) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manhua.Unmarshal(m, b)
}
func (m *Manhua) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manhua.Marshal(b, m, deterministic)
}
func (dst *Manhua) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manhua.Merge(dst, src)
}
func (m *Manhua) XXX_Size() int {
	return xxx_messageInfo_Manhua.Size(m)
}
func (m *Manhua) XXX_DiscardUnknown() {
	xxx_messageInfo_Manhua.DiscardUnknown(m)
}

var xxx_messageInfo_Manhua proto.InternalMessageInfo

func (m *Manhua) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Manhua) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *Manhua) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Manhua) GetChapter() string {
	if m != nil {
		return m.Chapter
	}
	return ""
}

func (m *Manhua) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Manhua) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

func init() {
	proto.RegisterType((*Manhua)(nil), "elasticsearch.Manhua")
}

func init() {
	proto.RegisterFile("elasticsearch/m_manhua.proto", fileDescriptor_m_manhua_1f18ee04dbaec3ce)
}

var fileDescriptor_m_manhua_1f18ee04dbaec3ce = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcd, 0x49, 0x2c,
	0x2e, 0xc9, 0x4c, 0x2e, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0xd0, 0xcf, 0x8d, 0xcf, 0x4d, 0xcc, 0xcb,
	0x28, 0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x91, 0x55, 0xea, 0x61, 0xe4,
	0x62, 0xf3, 0x05, 0xcb, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x04, 0x31, 0x79, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0x04, 0x67, 0x96, 0xa4, 0x4a, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0x7e, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12,
	0xcc, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x90, 0x04, 0x17, 0xbb, 0x73, 0x46, 0x62, 0x41,
	0x49, 0x6a, 0x91, 0x04, 0x0b, 0x58, 0x39, 0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x1a, 0x92, 0x59, 0x92,
	0x93, 0x2a, 0xc1, 0x0a, 0x16, 0x87, 0x70, 0x40, 0xe6, 0x84, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0x4a,
	0xb0, 0x81, 0x85, 0xa1, 0xbc, 0x24, 0x36, 0xb0, 0x23, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x6e, 0x6d, 0x19, 0xc4, 0x00, 0x00, 0x00,
}
